-- Kolom detail SIE (MobileMerchant StudentRequest)
-- Otomatis di-ALTER oleh aplikasi saat sinkron; file ini untuk referensi / manual.

USE malang_artri_face;

ALTER TABLE siswa ADD COLUMN IF NOT EXISTS num2nd VARCHAR(64) NULL COMMENT 'NUM2ND SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS stcust VARCHAR(32) NULL COMMENT 'STCUST SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS code01 VARCHAR(64) NULL COMMENT 'CODE01 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS desc01 VARCHAR(255) NULL COMMENT 'DESC01 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS code02 VARCHAR(128) NULL COMMENT 'CODE02 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS desc02 VARCHAR(128) NULL COMMENT 'DESC02 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS code03 VARCHAR(64) NULL COMMENT 'CODE03 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS desc03 VARCHAR(128) NULL COMMENT 'DESC03 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS code04 VARCHAR(64) NULL COMMENT 'CODE04 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS desc04 VARCHAR(128) NULL COMMENT 'DESC04 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS code05 VARCHAR(64) NULL COMMENT 'CODE05 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS desc05 TEXT NULL COMMENT 'DESC05 SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS totpay VARCHAR(64) NULL COMMENT 'TOTPAY SIE';
ALTER TABLE siswa ADD COLUMN IF NOT EXISTS genus VARCHAR(32) NULL COMMENT 'GENUS SIE';
